project_id = "jdbprivzprvpfoxrfyjy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.ai-booking]
verify_jwt = false

[functions.vapi-phone]
verify_jwt = true

[functions.transfer-call]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[functions.clean-ai-env]
verify_jwt = true

[functions.retell-webhook]
verify_jwt = false

[functions.create-retell-agent]
verify_jwt = true

[functions.retell-phone]
verify_jwt = true