// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdbprivzprvpfoxrfyjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkYnByaXZ6cHJ2cGZveHJmeWp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODE0NjgsImV4cCI6MjA3MjM1NzQ2OH0.rCjuQmuWSpychlhDOdpmmtMFwsyO2ab3x36FAS0NFNU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});